### PR TITLE
API for backend artists

### PR DESCRIPTION
**Pull request by andela-tolotin**
### Tasks to be completed
- Define the route for artist and album
- create migrations
- create class entity for Album, Artist and Song
- Return the right status code
- Create Repository and Inject them via the class constructor

### Results
screencapture-127-0-0-1-8001-album-2018-09-07-09_10_14
screencapture-127-0-0-1-8001-album-cmlmtl-2018-09-07-09_10_39
screencapture-127-0-0-1-8001-artist-2018-09-07-09_10_54
screencapture-127-0-0-1-8001-artist-k8q84q-2018-09-07-09_11_28

### Additional Installation
- Install serializer for returning proper JSON response
- Install Property Access to easy normalization of the class entity  and relationships

### CODE REVIEW

**Comment by fightbulc** [comment]
@andela-tolotin thanks for the PR. Still missing your feedback as requested:

`Finished or unfinished we would like to see your result and a couple of words of feedback from your end in order to get a better understanding of your thought process.`

**Comment by andela-tolotin** [comment]
@fightbulc 
I've added some screenshots of the JSON responses per resource (Artist and Album).

I like the concept of developers coming up with solving a real-life problem like this and it's really awesome. I would have loved to add some tests(TDD) to the solution but 3hrs was a short one to demonstrate that. 

It's also a learning curve for me during the data transformation and had to learn how to use serializer sweet functionality of helping to transform data among complex entities and converting them into a JSON response.

I think it would be better to remove the 3hrs barrier so as to allow the developer to be more creative and cover more edge cases.

I enjoyed the overall problem set and had fun during the implementation.

**Comment by fightbulc** [comment]
@andela-tolotin Thanks for the feedback and the taken time. We took a look and made the decision that you don't meet the requirements of the position we are looking to fill. Greetings from Berlin.

**Comment by andela-tolotin** [comment]
Hi, @fightbulc Thanks for giving me the opportunity to learn from this test. I will appreciate it if appropriate feedback can be provided: what did I not do well and what I did well. Thanks.

**Comment by fightbulc** [comment]
Hey @andela-tolotin a couple of notes:

You should read the assignment more carefully and don't be afraid to ask questions
for the clarification of the task. You've overlooked the critical part of the assignment -
making sure that generated token is unique.

You're not utilizing PHP 7+ typing capabilities to full extent, that's why you have to have
`instanceof` checks. Explicit typing of arguments and using explicit return types would save
you a lot of headache. But at the same time, using optional modifier for return type declaration
for every property is an indication of poor design and makes explicit type declaration useless.

Your controllers are not DRY, because you didn't read the serializer manual through to the end. You can use annotations on entities, to avoid having to manually configure normalizer in every controller action. Explicitly defining the normalizer and encoder is something that you must do only in edge cases.

Doctrine:
Please read more on how Doctrine works, what is the difference between Doctrine and any
other Active Record ORM. Unsetting related entity ID is not going to delete entity from DB without
proper orphan removal handling.

You don't have to define repository without custom logic. You can just use default EntityRepository and get it with EntityManager::getRepository($entityClass);

HTTP and routing:
You should indicate the specific HTTP method in route definition. Becase if you leave your endpoints available for access with multiple methods - that kinda defies the whole purpose of REST.

https://ocramius.github.io/doctrine-best-practices/#/
https://ocramius.github.io/blog/fluent-interfaces-are-evil/
https://phptherightway.com/

**Comment by andela-tolotin** [comment]
@fightbulc Thanks for the feedback

**Pull request closed without merging**
