### PR TITLE
Leonardolasouza application backend artists

### PR DESCRIPTION
**Pull request by leonardolasouza**
Hi,

Thank you very much for the test.
This is unfinished as it was requested to stop it after 3 hours of working time.

It is a good test to assess some skills about doctrine, fixtures, request methods, ....
It would  be nice to add more time for this test as there are too many details to be done.

Feel free to give any feedback for me as well.

Kind regards,

### CODE REVIEW

**Comment by fightbulc** [comment]
Hey @leonardolasouza. Thanks for the taken time.

I think most of the things for this test are boilerplate code and that's fine. The test is not about finishing it. The test should tell me how you work with Git, your code and your general approach. In the description we are asking for your thought process since I am interested in understanding your steps. It seems that you didn't take the time to read through the description carefully because I am missing your feedback on your steps/thoughts.

Symfony is listed in your ` Preferred technologies` on talent.io but I am not sure what's your level of experience here. Your response in the `AlbumController` can be done via `Groups` defined in your Doctrine repository and the `Serializer`. Groups would keep both worlds decoupled because right now you're building an array response by hand. What happens when property names change?

The way you request the repositories could be done by either setting them as method parameters or by requesting the objects at the beginning of the method. However, the `AlbumRepository` is requested over and over again in the foreach loop. With that you can also see that your Controller ist not DRY since requesting the repository is repeating the same code.

I see that you're trying to build the song length in seconds as requested. Why is the `length` property i your `Songs` entity defined as a `string`?

One major piece of the test is to make sure that `tokens` are unqiue for Artists and Albums.
This hasn't been addressed.

So @leonardolasouza, unfortunately I am not seeing what we are looking for in the offered position.

Greetings

**Comment by leonardolasouza** [comment]
Hi Tino,

You're welcome and thanks for giving me a detailed feedback. Really, I appreciate it!

I would like just to mention a couple of things about what you wrote, regardless the final result.
The decision is already taken and I'm totally fine with that.
It's just some comments from a candidate's perspective and some answers for your questions:

"...It seems that you didn't take the time to read through the description carefully because I am missing your feedback on your steps/thoughts."
   Yes, I did it.
   Based on README.md: "Finished or unfinished we would like to see your result and a couple of words of feedback from your end in order to get a better understanding of your thought process.", I wasn't expecting to describe the way I provided the solution.
   May it helps to another ones to mention: "Finished or unfinished we would like to see your result and a couple of words about the key steps about the implementation of your solution".
   Or something more clear to state the steps, the major important points.
   
"Symfony is listed in your Preferred technologies on talent.io"
   From my understanding, a "Preferred technologies" is about to work with, not the ones which I have experience.
   It's not mention on my working experience for sure!
   It's just a framework which I'm willing to start to work with as I have zero professional experience with this one.
   
Comments how to approach some tasks in Symfony / Doctrine ("Groups", " Serializer", ...)
   So good to know about that. Thank you so much Tino!
   
"Song length"
   You're right. It's a mistake.
   As I defined the database via migrations based on the data structure, I forgot to update it. Just a mistake that happens.
   
"Tokens are unique":
   I did know that.
   As it is really simple thing to implement on the code AppFixtures::load(). I skiped it to implement the API and not to spend the whole time in loading data for this exercise.
   (create a function to generate it and check if it exists or not in a class member (array) as much as we need (no need database in that case))
   

Anyway, always learning and thanks for the opportunity ;-).
That's fine.

Cheers

**Comment by leonardolasouza** [comment]
Hi Tino,

Just an update abput the item "Symfony is listed in your Preferred technologies on talent.io":
  I spoke to talent.io staff (Erik) and it's about what I'm interested in.

  As I candidate I don't have the same view as you do but what they told me is that important to the companies read the whole profile, like the sections "What 'candidate' has done" and "What 'candidate' wants go" to avoid problems.

  Hope this helps you on next time.

Cheers

**Comment by fightbulc** [comment]
Morning Leonardo.

Thanks for the clarification regarding talent.io's "Preferred technologies". To me this doesn't sound like "Things I'd like to work with but haven't yet". I'll give them some feedback.

We want that people learn and grow, that's a natural process and we support that. For that reason
we requested to share their "thoughts" with us so that understand whats going on even though they didn't finish the task. Take a look at your first feedback. Any thought process there to `get a better understanding`?

Anyway, appreciate your feedback. Always good to get some feedback also from the other side.

All the best for the future.
Tino

**Comment by leonardolasouza** [comment]
Hi Tino,

No worries, it's all set.

Yes, give them some feedback as it can lead to some misunderstanding, for sure you are not the first one.

Cheers

**Pull request closed without merging**
