### PR TITLE
Finished application

### PR DESCRIPTION
**Pull request by jacMelloni**
Pretty fun exercise, I think I had time to implement all the specifications except ensuring that the token will be unique among both Artists and Albums (right now there's just a Unique constraint on each table): I would have liked to implement something more elegant than simply checking both tables before persisting each entity in the Fixtures, but I run out of time before I could think of something else.

I divided the task in 3 steps:
- Entity and DB creation
- Fixture loading 
- Endpoint creation

If I had a bit more time I would have probably gone back to the 2nd step and moved the storage logic for each Entity from the Fixture to the Repositories.

### CODE REVIEW

**Comment by fightbulc** [comment]
@jacMelloni Hey there. Thanks for handing in your test. What's your name so I can connect you to our applicants?

**Comment by jacMelloni** [comment]
Hi sorry about that, I forgot to update my profile!
I'm Jacopo Melloni

**Comment by fightbulc** [comment]
Thanks Jacopo. We'll get back to you. Have a nice weekend!

**Comment by fightbulc** [comment]
@jacMelloni what would be your suggestion to `something more elegant than simply checking both tables`?

**Comment by jacMelloni** [comment]
> @jacMelloni what would be your suggestion to `something more elegant than simply checking both tables`? Also, how would you rate your experience with Symfony4 and Doctrine and PHP7 in general?

I think right now I would move the token to an external Entity with a Unique constraint on the value, this way both Artists and Albums would reference to it using Foreign keys and I could possibly manage duplicates using LifecycleCallbacks...

Unfortunately I do not have a lot of experience on Symfony4 and PHP7, I am still working on older platforms (PHP 5.4 + Symfony2)... I do have some good work experience with Doctrine

**Pull request closed without merging**
